# Generated by Django 2.2.6 on 2019-10-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgpath',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
