# Generated by Django 2.2.6 on 2019-11-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_contacts_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='course.Course'),
        ),
    ]
